
server:
  servlet:
    context-path: /webhookproxy/api
  error:
    include-message: never
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto

logging:
  level:
    org.springframework: ${LOGLEVEL_SPRING:INFO}
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.boip.util.webhookproxy: ${LOGLEVEL_APPLICATION:INFO}

management:
  health:
    db:
      enabled: false
    ldap:
      enabled: false
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
#    metrics:
#      enabled: true
#    prometheus:
#      enabled: true
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  server:
    port: 8090

github:
  secret: ${GITHUB_SECRET}

target:
  url: ${TARGET_URL}

app:
  skip_validation: ${SKIP_VALIDATION:false}